name: "Build legacy Nix package on Ubuntu"

on:
  push:

jobs:
  build:
    runs-on: nixos/nix
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v15
      - name: Building package
        run: nix build 
